# Generated by Django 5.2.1 on 2025-07-03 14:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contest",
            options={"verbose_name": "Contest", "verbose_name_plural": "Contests"},
        ),
        migrations.AddField(
            model_name="contest",
            name="registration_end",
            field=models.DateTimeField(default=datetime.datetime(1234, 5, 6, 7, 8, 9)),
        ),
        migrations.AddField(
            model_name="contest",
            name="registration_start",
            field=models.DateTimeField(default=datetime.datetime(1234, 5, 6, 7, 8, 9)),
        ),
        migrations.AddField(
            model_name="contest",
            name="year",
            field=models.IntegerField(
                default=2025,
                help_text="比赛举办年份",
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2200),
                ],
            ),
        ),
    ]
