# Generated by Django 5.2.1 on 2025-07-20 06:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0002_alter_contest_options_contest_registration_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
