# Generated by Codex on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="official_registration_completed",
            field=models.BooleanField(default=False, help_text="是否已在比赛官网报名"),
        ),
    ]
