# Generated by Django 5.2.1 on 2025-07-09 05:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userteam",
            name="join_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="加入队伍的日期",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="team",
            name="existing_members",
            field=models.PositiveIntegerField(default=1, help_text="队伍已有人数"),
        ),
        migrations.AlterField(
            model_name="team",
            name="expected_members",
            field=models.PositiveIntegerField(help_text="队伍期望人数"),
        ),
        migrations.AlterField(
            model_name="team",
            name="invitation_code_created_at",
            field=models.DateTimeField(auto_now=True, help_text="邀请码创建时间"),
        ),
        migrations.AlterField(
            model_name="team",
            name="recruitment_deadline",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="招募截止日期"
            ),
            preserve_default=False,
        ),
    ]
