# Generated by Django 5.2.1 on 2025-07-12 02:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_userteam_join_date_alter_team_existing_members_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="invitation_code_created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="邀请码创建时间"
            ),
        ),
    ]
