# Generated by Django 5.2.1 on 2025-07-26 11:02

import SJTUcontest.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_team_created_at_team_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="invitation_code",
            field=models.CharField(
                default=SJTUcontest.utils.generate_random_string,
                help_text="队伍邀请码",
                max_length=40,
            ),
        ),
    ]
