# Generated by Django 5.2.1 on 2025-09-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_alter_team_invitation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="introduction",
            field=models.CharField(
                blank=True, help_text="队伍简介", max_length=500, null=True
            ),
        ),
    ]
