# Generated by Django 5.2.1 on 2025-08-30 12:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="新闻标题", max_length=100)),
                ("summary", models.TextField(help_text="新闻摘要")),
                ("url", models.URLField(help_text="新闻链接")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="新闻创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="新闻更新时间"),
                ),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
            },
        ),
    ]
