# Generated by Django 5.2.1 on 2025-06-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "用户", "verbose_name_plural": "用户"},
        ),
        migrations.AddField(
            model_name="user",
            name="jaccount_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="jAccount账号"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="student_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="学工号"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="身份类型"
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="users_user",
        ),
    ]
