# Generated by Django 5.2.1 on 2025-06-28 07:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options_user_jaccount_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="jaccount_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="student_code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_type",
        ),
    ]
