# Generated by Django 5.2.1 on 2025-09-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="advantage",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="特长"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="experience",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="参赛经历"
            ),
        ),
    ]
