# Generated by Django 5.2.1 on 2025-09-22 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_advantage_alter_user_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="advantage",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="特长"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="experience",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="参赛经历"
            ),
        ),
    ]
